### PR TITLE
Testimonial Section

### PR DESCRIPTION
**Pull request by PANDEYS432**
Testimonial Section is implemented

### CODE REVIEW

**Comment by PANDEYS432** [comment]
> 

testimonials component

**Comment by NeerajChatterjee** [comment]
image
- The name and designation is not looking good at this viewport. So, try the mobile view layout before 640px only.

image
- Make it look attractive by adding a bit of styling and also make the message vertical center as, the bottom space is empty.

image
- Try to make this type of button instead of the one that's used and use some hover effects on buttons (prev and next).

**Review by sanskaromar — COMMENTED** [review]
Rename your PR to something like Testimonial section.

**Comment by PANDEYS432** [comment]
Screenshot (521)
Screenshot (522)
Screenshot (523)
Screenshot (524)

**Review by NeerajChatterjee — CHANGES_REQUESTED** [review]
Screenshot 2023-02-13 024056

- Make the layout like this, as the existing one doesn't look good. Also, make the quote image bigger, similar to what you can see in the picture.

image
 - See the designation text (Head strategy & New Initiatives...), make it align center and cross check the same with every card before the push.

image

- Just a small change to increase the gap between the arrows and the container at mobile view, so that arrows don't stack over container.

**Comment by PANDEYS432** [comment]
Screenshot (528)
Screenshot (529)
Screenshot (530)
Screenshot (531)

**Pull request merged**
